#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def closestNumbers(arr):
    # Write your code here
    arr.sort()
    dicts = {}
    
    for j in range (0,len(arr)-1):
        if arr[j]-arr[j+1] not in dicts:
            dicts[arr[j]-arr[j+1]] = []
        dicts[arr[j]-arr[j+1]].append([arr[j],arr[j+1]])
        # print(dicts)
    lists = sorted(dicts)
    l = dicts[lists[-1]]
    # print(l)
    jj = []
    for i in l:
        jj.append(i[0])
        jj.append(i[1])
        # print(jj)
    return jj
    
                
            
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
