#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'repeatedString' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def repeatedString(s, n):
    # Write your code here
    count = 0
    for i in s:
        if i == "a":
            count = 
            
    if len(s) < n:
        if n % len(s) == 0:
            m = n // len(s)
            new_s = s * m
        else:
            m = (n // len(s))
            new = s * m
            new_s = new + new[0]
        for i in new_s:
            if i == "a":
                count +=1
        return count
    elif len(s)>= n:
        for j in range(n):
            if s[j] == "a":
                count +=1
        return count
    
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
