#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#

def bonAppetit(bill, k, b):
    # Write your code here
    # print(bill)
    ba = 0
    bb = 0
    bill.remove(bill[k])
    # print(bill)
    for i in bill:
        ba += i
        # print(ba)
    bb = ba//2
    # print(bb)
    if b > bb:
        # print(b)
        bi = int(b-bb)
        print(bi)
    elif b == bb:
        print("Bon Appetit")
    else:
        print(int(b-bb)) 
        

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
